CREATE USER tutor IDENTIFIED BY "tutor" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO tutor;
GRANT CREATE TABLE TO tutor;
GRANT CREATE VIEW TO tutor;
GRANT CREATE SEQUENCE TO tutor;
GRANT CREATE PROCEDURE TO tutor;
GRANT CREATE TRIGGER TO tutor;
GRANT CREATE TYPE TO tutor;
GRANT CREATE JOB TO tutor;