CREATE SEQUENCE person_sq START WITH 100;
CREATE SEQUENCE subject_sq START WITH 100;
CREATE SEQUENCE adress_sq START WITH 100;
CREATE SEQUENCE language_sq START WITH 100;
CREATE SEQUENCE translation_sq START WITH 100;
